FROM rabbitmq

RUN rabbitmq-plugins enable --offline rabbitmq_management
# RUN echo management_agent.disable_metrics_collector = false > management_agent.disable_metrics_collector.conf 

EXPOSE 15671 15672